[default]

[development]
aws_access_key_id = ''
aws_secret_access_key = ''
SMTP_HOST="smtp.mailtrap.io"
SMTP_PORT=2525
SMTP_USER=""
SMTP_EMAIL=""
SMTP_PASSWORD=""
SMTP_MSG_FROM=""
SMTP_FROM_NAME="Projeto Tarefas"
SMTP_TLS = false

[production]
aws_access_key_id = ''
aws_secret_access_key = ''
SMTP_HOST="smtp.mailtrap.io"
SMTP_PORT=2525
SMTP_USER=""
SMTP_EMAIL=""
SMTP_PASSWORD=""
SMTP_MSG_FROM=""
SMTP_FROM_NAME="Projeto Tarefas"
SMTP_TLS = false