[default]
# see at https://www.dynaconf.com/#on-env-vars
CURRENT_ENV = "@jinja {{this.current_env | lower}}" # development or production
HOME_DIR = "@jinja {{env.HOME}}"
DIR_INPUT="Entrada"

APP_NAME="Tarefas Background! 🚀"
APP_VERSAO="1.0.0"
APP_DESCRIPTION="API Aprendendo Celery ! 🇧🇷"

URL_CHECK_PUBLIC_IP = "https://ifconfig.me"
URL_API_CRYPTOMOEDA = "https://ifconfig.me"
DIR_OUTPUT_CRYPTO="@jinja {{this.HOME_DIR}}/output_crypto"


DIAS_SEMANA = [ "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado", "Domingo",]
