version: "3.8"

networks:
  web:
    external: true

services:
    redis:
        container_name: "redis"
        image: redis:6-alpine
        ports:
            - '6379:6379'
        networks:
            - web
        # Here we define our settings for traefik how to proxy our service.
        labels:
          # This is enableing treafik to proxy this service
          - "traefik.enable=false"
      
